name: Windows - RustDesk

on:
  .github/workflows:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 9999


      - name: Log In To AnyDesk
        run: cmd /c show.bat

      - name: Time Counter
        run: python time.py
